apiVersion: apps/v1
kind: Deployment
metadata:
  name: tictacto
  labels:
    app: tictacto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tictacto
  template:
    metadata:
      labels:
        app: tictacto
    spec:
      containers:
      - name: tictacto
        image: redheaven/tictacto:latest
        ports:
        - containerPort: 8080
        env:
        - name: ENVIRONMENT
          value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: tictacto-service
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: tictacto
